### ISSUE TITLE
[Milestone]: Paper Outline

### ISSUE THREAD

**Issue by ababaian** [serratus-bio/open-virome#98]
**Sprint Milestone**: Set-up a draft/outline of the Hyper-Virome paper to provide strategic planning for the following ~8 sprints. The main outcome here will be to create a kind of `List` of major tasks (i.e. populate the backlog) so that we can allocate which features will be `must have` and which will be `nice to have` and group them into relevant topics. This will allow for planning of person-time per sprint block so one person can do a group of tasks all together.

This will require input from everyone, with major tasks coming from @lukepereira 

- [x] Set-up paper overleaf - @lukepereira 
- [x] Draft/outline intro - @lukepereira 
- [ ] 2 figures mock-up; short text description for it - @ababaian @almosnow @lukepereira  (each)
- [ ] Biological use-case - Apicomplexa (?)

**Comment by lukepereira** [comment]
I set up the manuscript using our previous template, will share in DMs

I can transfer the document to a.babaian@utoronto.ca later, since i think that was the premium account with track changes, faster compile, etc.

I will be working on drafting the intro and outline later this week

**Comment by lukepereira** [comment]
Meeting notes

TODO:
- [x] Transfer overleaf doc [Luke, Artem]
- [ ] Open project module for Palmdb v3 on Logan [Artem] 
- [x] Reach out to Jonathan about colab [Artem] 
- https://github.com/serratus-bio/open-virome/issues/122 [Luke]
- https://github.com/serratus-bio/open-virome/issues/123 [Luke] 

Overview:
1.  [Artem] Palmdb Logan Summary statistics
2. [Luke, Alex] Knowledge graph, virus-metadata integration
3. [Alex, Jonathan] Kadipiro search
4. [Luke] Embedding-based recommendations



Scrap

```
Metadata available:
- Tissue
- Geography (Biome)
- Host Taxonomy
- Virus Taxonomy
- pH 
- Temperature
- Sex
- STAT Host
- SRA Run info 
- [?] Interferon (recount)
- [?] Disease


Key results
1. sOTU counts, metadata associations, histogram, summary stats
2. Demonstrate integration of metadata and sOTUs, Virus Characterization  
   - Biological use case characterization: Kadipiro virus, 
   - NK cell -> Kadipiro
   - https://www.ncbi.nlm.nih.gov/bioproject/746336

1.. Runs, 2. phylogenetic 3. Find more things/branching out
```
